language: python
python:
  - "3.6"
  - "3.8"
addons:
  sonarcloud:
    organization: "ksekator"
    token: a11ec8ac122d2b04dd26ee22fa23eb3877a8837a
install:
  - pip install pymorphy2
  - pip install unittest2
  - pip install coveralls
  - pip install pytest
  - pip install pytest-pep8
  - pip install pytest-cov
  - pip install httpretty
script:
  - python main.py
  - sonar-scanner -X
  - py.test coveralls/main.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
