language: python
python:
  - "3.6"
  - "3.8"
addons:
  sonarcloud:
    organization: "ksekator"
    token: a11ec8ac122d2b04dd26ee22fa23eb3877a8837a
install:
  - pip install pymorphy2
  - pip install unittest2
script:
  - python main.py
  - sonar-scanner -X
after_success:
  - coveralls
